export const SIDEBAR_OPEN = "SIDEBAR_OPEN";
export const SIDEBAR_CLOSE = "SIDEBAR_CLOSE";
export const SEND_USER_TO_CONTEXT = "SEND_USER_TO_CONTEXT";
export const SEARCHING_FOLLOWERS = "SEARCHING_FOLLOWERS";
export const END_SEARCHING_FOLLOWERS = "END_SEARCHING_FOLLOWERS";
export const LOAD_FOLLOWERS = "LOAD_FOLLOWERS";
